language: python

python:
    - "3.9"
env:
    - SECRET_KEY='TEST'
services:
    - postgresql

install:
    - pip3 install -r requirements.txt

script:
    - coverage run --source ="authentication"python3 manage.py test && coverage

after_success:
    - codecov

    